[package]
org = "wso2"
name = "ecemployeecentralpayroll_connector_sample"
version = "0.1.0"
distribution = "2201.13.1"
title = "ecemployeecentralpayroll-connector-sample"

[build-options]
sticky = true
