[package]
org = "wso2"
name = "sap.businessone.financials_connector_sample"
version = "0.1.0"
distribution = "2201.13.4"
title = "sap.businessone.financials-connector-sample"

[build-options]
sticky = true

