[package]
org = "wso2"
name = "ballerinax_hubspot_events_completions_connector_sample"
version = "0.1.0"
distribution = "2201.13.5"
title = "ballerinax_hubspot_events_completions_connector_sample"

[build-options]
sticky = true
