[package]
org = "wso2"
name = "sap.s4hana.sales.order.analytics_connector_sample"
version = "0.1.0"
distribution = "2201.13.1"
title = "sap.s4hana.sales.order.analytics-connector-sample"

[build-options]
sticky = true
