[package]
org = "wso2"
name = "java.jms_message_producer_connector_sample"
version = "0.1.0"
distribution = "2201.13.1"
title = "java.jms-message-producer-connector-sample"

[build-options]
sticky = true
