[package]
org = "wso2"
name = "sap.s4hana.api_sales_order_simulation_srv_connector_sample"
version = "0.1.0"
distribution = "2201.13.1"
title = "sap.s4hana.api_sales_order_simulation_srv-connector-sample"

[build-options]
sticky = true
