[package]
org = "wso2"
name = "hubspot.marketing.subscriptions_connector_sample"
version = "0.1.0"
distribution = "2201.13.1"
title = "hubspot.marketing.subscriptions-connector-sample"

[build-options]
sticky = true
